---
- include: timezone_redhat_6.yml tags=timezone
  when: ansible_os_family == 'RedHat'
        and ansible_distribution_major_version == '6'

- include: timezone_redhat_7.yml tags=timezone
  when: ansible_os_family == 'RedHat'
        and ansible_distribution_major_version == '7'
